mod 'puppetlabs/puppet_agent', :latest
mod 'puppetlabs/java', :latest
mod 'puppetlabs/apache', :latest
mod 'puppetlabs/vcsrepo', :latest
mod 'puppetlabs/powershell', :latest
mod 'puppetlabs/stdlib', :latest
mod 'puppetlabs/git', :latest
mod 'puppetlabs/puppetserver_gem', :latest
mod 'puppetlabs/concat', :latest
mod 'puppetlabs/pe_gem', :latest
mod 'puppetlabs/aws', :latest
mod 'puppetlabs/splunk', :latest
mod 'puppetlabs/inifile', :latest
mod 'puppetlabs/apt', :latest
mod 'puppetlabs/firewall', :latest
mod 'puppet/collectd', :latest
mod 'puppet/iis', :latest
mod 'puppet/archive', :latest
mod 'jfryman/puppet-nginx', :latest
